<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "galerie_ghtpr"
 *
 * Auto generated by Extension Builder 2019-06-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'galerie-photo-cms',
    'description' => 'Une super galerie d\'image pour Typo 3 : projet DAWIN',
    'category' => 'plugin',
    'author' => 'Robin Marius, Petit Quentin, Bastien Tebbani, Anthony Guichard, Charlie Hauselmann',
    'author_email' => 'marius.robin@etu.u-bordeaux.fr, quentin.petit@u-bordeaux.fr, bastien.tebbani@etu.u-bordeaux.fr, anthony.gichard.1@etu.u-bordeaux.fr, charlie.hauselmann@etu.u-bordeaux.fr',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
